### ISSUE TITLE
Building app-debug.apk

### ISSUE THREAD

**Issue by jringbox** [m0dch3n/vue-cli-plugin-cordova#111]
Great plugin.  One issue.  How do I build a debug apk?  The only way I figured out how to build one is to "cordova-serve-android" then then terminate the emulator when it comes up.  Is there another way?

I tried adding a new script like this.

"cordova-build-android-dev": "cross-env NODE_ENV=development CORDOVA_PLATFORM=android vue-cli-service --mode development cordova-build-android-dev"

But, this didn't work.  So, I don't know how to get this built without having to doing a "serve".

**Comment by sunlix** [comment]
Hey @jringbox try this:

```
"scripts": {
"build:android": "cross-env CORDOVA_PLATFORM=android vue-cli-service cordova-build-only-www-android --mode development && cordova build android --debug"
}
```

**Comment by m0dch3n** [comment]
If your devserver is not running, your `dev` apk will still point to an `IP:PORT` which is not responding... So I don't see any need for this scenario...

Anyway, usually when I need to rebuild only the dev apk, without the vuejs stuff, i.e. because I needed to change things on the native cordova part (like a new cordova plugin) I first run `cordova-serve-android` and later I just open the android project under `src-cordova/platforms/android` with android studio and build it from there, so that only the apk get's rebuild... 

Same goes for IOS, I just open the project under Xcode...

PS: I you **DON'T** want your dev apk to point to your devserver, but to the apk contents under `file:///android_asset/www/index.html` don't use any `cordova-serve-*` command from this plugin, because they modify your `config.xml` to point to your devserver.... 

In that case `cordova-build-only-www-android` and a manual build directly from cordova is more considerable like @sunlix suggested... 

`cordova-build-only-www-android` generates a static build of your vue app, to the `www` folder of cordova

**Comment by jringbox** [comment]
@sunlix That didn't work.  I would like that command to work.  Would simplify my scripting for jenkins build.

@m0dch3n I did this and it appeared to build what I wanted.

npm run cordova-build-only-www-android
cd src-cordova
cordova build android

Too bad there's not a script for this but then again I'm sure there are so many permutations of what everyone wants for a build that you can't please everyone.

**Comment by m0dch3n** [comment]
> Too bad there's not a script for this but then again I'm sure there are so many permutations of what everyone wants for a build that you can't please everyone.

Yes, basically the problem is, to build your `vue.js cordova app`, you need to run 2 commands... One to build vue.js (javascript part), and one to build cordova (native part)

That's what this plugin basically does and not more... It prepares your javascript app to include cordova.js, builds everything to src-cordova/www or serves from devserver, and then executes cordova build or run command.

For dev (cordova-serve-*) this means `vue serve && cordova run` and for production (cordova-build-*) `vue build && cordova build`. 

Combinations of `vue build && cordova run` or `vue serve && cordova build` are not supported by the plugin, as well as command params for the cordova command. All params are passed to the vue command. `--target` is the only param which is passed to cordova as param.

PS: 
```
npm run cordova-build-only-www-android
cd src-cordova
cordova build android
```
is the same then `cordova-build-android`
what you need to do is
```
npm run cordova-build-only-www-android
cd src-cordova
cordova build android --debug
```

**Comment by sunlix** [comment]
@jringbox in my case cordova-src is same as vuejs-src. Both located at project-root. In that case, building like I mentioned works fine. :)

**Comment by jringbox** [comment]
@sunlix Well your setup does not work in my project setup.  I get this.

```
Current working directory is not a Cordova-based project.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clinicallink-mobile@0.1.0 build:android: `cross-env CORDOVA_PLATFORM=android vue-cli-service cordova-build-only-www-android --mode development && cordova build android --debug`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the APP@0.1.0 build:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2020-04-01T13_59_54_089Z-debug.log
```
I wonder why it works for you.

I have to do it this way.

1.  I create a script like this under VueJS' package.JSON.  I have to do this since `cordova-build-android` builds for production and I want a development build.

```
    "cordova-build-android-debug": "cross-env CORDOVA_PLATFORM=android vue-cli-service cordova-build-only-www-android --mode development",
```

2.  Then I build like this.

```
npm run cordova-build-android-debug
cd src-cordova
cordova build android
```

**Comment by m0dch3n** [comment]
@jringbox try creating a www folder

**Comment by sunlix** [comment]
@jringbox yeah like @m0dch3n mentioned, check for folders "platforms", "plugins" and "www".
create them if they no exists.

**Comment by jringbox** [comment]
All those folders exist under src-cordova.

**Comment by sunlix** [comment]
If your `cordova-source-folder` differs from the `vue-source-folder` you have to execute the second command of the npm-script `cordova build android --debug` in scope of the `cordova-source-folder`.

I don't know if cordova have a current-working-directory attribute like `cordova build android --cwd="src-cordova" --debug` . Tools like `npm`or `yarn` have a cli-attribute `--cwd`.
You have to ensure to execute the `cordova` command in the correct directory.
