### ISSUE TITLE
Android@^5.0.0 is not supported

### ISSUE THREAD

**Issue by XieB** [m0dch3n/vue-cli-plugin-cordova#113]
now i want to build a app on android4.2.2，but the default version is 8.
I try to command
`
cordova platform remove android
cordova platform add android@^5.0.0
` 
then i got the error
`
BUILD SUCCESSFUL in 1s
2 actionable tasks: 2 up-to-date
 INFO  executing "cordova run android" in folder D:\code\cordova\vue-cordova\src-cordova
 INFO  updating D:\code\cordova\vue-cordova\src-cordova\platforms\android\app\src\main\res\xml\config.xml content to https://192.168.1.65:8080
ENOENT: no such file or directory, open 'D:\code\cordova\vue-cordova\src-cordova\platforms\android\app\src\main\res\xml\config.xml'
`
thanks

**Comment by m0dch3n** [comment]
This plugin is not compatible with android@^5.0.0, because this platform does not create platforms/android/app/src/main/res/xml/config.xml

Feel free, to create a PR to make it compatible, your starting point is here:

 https://github.com/m0dch3n/vue-cli-plugin-cordova/blob/e0c96921e41e059c325b5bd16ef8e2e778c01a7e/index.js#L199

**Comment by m0dch3n** [comment]
PS: Targeting such old android versions will also endup, making your created js webapp compatible. So make sure, your JS gets bundled and polyfilled correctly support vue.js etc
