### ISSUE TITLE
.obb expansion files

### ISSUE THREAD

**Issue by Navamaru** [m0dch3n/vue-cli-plugin-cordova#114]
I'm using this, in combination with vue-router and vuetify for an app, while everything works fine locally, I have problems with the Play Store since there is a file limit of 100mb for the .apk and 150mb for apk bundles, but since my app contains a lot of images i reach the size 170mb (with all the images compressed as much as possible), this forces me to create an expansion file where i have to put my images.
Now the thing that i can't get to work is how to then reference the images inside the expansion files inside my app, any ideas?

Thanks!

**Comment by m0dch3n** [comment]
No, I don't have any idea, because I was never in this case... But this is also more cordova problem, than related to this plugin... So I would consider to search in that community (which is much bigger), [ask google](https://www.google.com/search?sxsrf=ALeKk03Aj1qKauntkI8i9x9gMPxz1WvNIw%3A1587733449169&ei=yeOiXrXhCY-TkwW5pIDoBA&q=obb+expansion+files+cordova&oq=obb+expansion+files+cordova&gs_lcp=ChNtb2JpbGUtZ3dzLXdpei1zZXJwEAMyCAghEBYQHRAeOgQIABBHOgYIABAWEB46CAgAEBYQChAeOgUIIRCgAToECCEQFToHCCEQChCgAVDKD1iWMGDPMWgCcAF4AIABoAGIAakKkgEEMC4xMJgBAKABAQ&sclient=mobile-gws-wiz-serp) or within StackOverflow

**Comment by Navamaru** [comment]
Thanks for the suggestion, i'll see what can i find :)
