### ISSUE TITLE
scripts in index.html, dont run if a route is refreshed and isnt the base

### ISSUE THREAD

**Issue by aglopes-monitar** [m0dch3n/vue-cli-plugin-cordova#15]
as image show scripts in index.html, dont work if refresh a route...

![issues](https://user-images.githubusercontent.com/34067310/46298696-9ed08780-c597-11e8-84be-69b1074fc438.PNG)

**Comment by aglopes-monitar** [comment]
they workout just fine if follow app clicks...

**Comment by aglopes-monitar** [comment]
do i hv to import everything in app.vue?

**Comment by aglopes-monitar** [comment]
yes that worked...it going be a hard job... still wanna replace most components with vuetify

**Comment by m0dch3n** [comment]
static scripts, images etc from the "public" folder need to have the correct relative path to work correctly in index.html

Files included in main.js etc are build to app.js file from webpack

**Comment by aglopes-monitar** [comment]
in index.html under body tab:
<script src="<%= BASE_URL %>static/js/jquery-3.3.1.min.js"></script> 
if refresh a route in browser stop to work...
in vue.config.js i have:
module.exports = {
  baseUrl: '',
  pluginOptions: {
    cordovaPath: 'src-cordova'
  },
  devServer: {
    port: 7070
  }
}

**Comment by aglopes-monitar** [comment]
baseUrl: 'http://192.168.1.4:7070',

now i can refresh...

**Comment by aglopes-monitar** [comment]
allready able to run on android ... going generate apk to test! 
Nice plugin and thx for all

**Comment by m0dch3n** [comment]
On a default vue cli app, you need to put your jquery.js file i.e under public/static/js/jquery.js

Than you can use src="static/js/jquery.js"...

**Comment by aglopes-monitar** [comment]
Generated unsigned apk ... Wasnt able to install, then opened project
android with android studio, to try run it kinda after gradle build.
generated a debug apk and runed on device but none of JavaScript worked..
note everything was well on browser and cellphone when Run serve android.
also before generate apk i did build android ... Then went out off worktime


A segunda, 1/10/2018, 20:55, m0dch3n <notifications@github.com> escreveu:

**Comment by m0dch3n** [comment]
if you are unable to install the apk, it's normally because an app, with the same id, with a different dev signature exists already on the phone... nevertheless, I can't help you here, and I think, this is more cordova related, than to plugin...

Please correct me with more detailed error message then "I wasn't able to install"

JFYI 

when you do `npm run cordova-serve-android` the plugin is only starting a webserver, and pointing config.xml of cordova to your dev server, and running the command `cordova run android`... If `cordova run android` fails, this has nothing to do with the plugin, but with cordova 

If javascript is not working, or you have a blank page, normally you have incorrect paths, or your devserver does not correctly serve them, or in a production build, the files are maybe not included, due to some webpack configuration etc...

BTW

with chrome you can remote debug your dev app, to see if paths are correct etc... 

https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

I'll stop now supporting this issue, because I feel, that it's more related to your specific setup, than to the plugin. If I'm wrong, than sorry, but than you need to provide more details, like console outputs, error messages, etc...

**Comment by aglopes-monitar** [comment]
do everything needs to be in css or js folder?
or we can just make folder on static named libraries for example?

André Lopes <aglopes.monitar@gmail.com> escreveu no dia segunda, 1/10/2018
à(s) 22:17:

**Comment by m0dch3n** [comment]
https://cli.vuejs.org/guide/html-and-static-assets.html

**Comment by aglopes-monitar** [comment]
am using android studio just to debug to find out...
it looks like all my vars go null even when declare data(){
return{
     cliped:true,
     api_key: 'xxxxx-yyyyy'
}}
it didnt mixin the api-key to http requests(wondering why...)
i did atemp an auth

2018-10-01T22:34:06.339Z - error: response: No Sense API Key response sent
2018-10-01T22:34:06.343Z - http: POST "/api/v1/authentication" HTTP/1.1
[::ffff:192.168.1.4] 200 61 "-" "Mozilla/5.0 (Linux; Android 8.0.0; Android
SDK built for x86 Build/OSR1.170901.043; wv) AppleWebKit/537.36 (KHTML,
like Gecko) Version/4.0 Chrome/69.0.3497.91 Mobile Safari/537.36"

the main.js code:

import Vue from 'vue';
import './plugins/vuetify'
import App from './App.vue';
import router from './router';
import VueResource from 'vue-resource';
import {setToken, getToken, getValidToken} from './token';
import {ServerTable, ClientTable, Event} from 'vue-tables-2';
import 'roboto-fontface/css/roboto/roboto-fontface.css'
import 'material-design-icons-iconfont/dist/material-design-icons.css'
import '@fortawesome/fontawesome-free/css/all.css'
Vue.config.productionTip = false;
Vue.config.devtools = false;

const config =  {
  /*http_path: process.env.VUE_APP_HTTP_PATH,
  map_key: process.env.VUE_APP_MAPS_API_KEY,
  sense_key: process.env.VUE_APP_SENSE_API_KEY*/
  http_path: 'http://192.168.1.4:8080/api/v1',
  map_key: 'this is private',
  sense_key: 'this is private'
};

Vue.use(VueResource);
Vue.http.options.root = config.http_path;
Vue.http.interceptors.push((request, next) => {
  request.headers.set('Accept', 'application/json');
  request.headers.set('Api-Key', config.sense_key);
  var token = getToken();
  if(token) {
    request.headers.set('x-access-token', token);
  } else {
    router.push('/auth/login');
  }
  next()
});

const eventHub = new Vue ();

Vue.mixin({
  data: function () {
    return {
      config,
      eventHub
    }
  }
});
/*
Vue.use(ClientTable, {}, false, 'bootstrap4');
Vue.use(ServerTable, {}, false, 'bootstrap4');
*/
new Vue({
  router,
  config,
  render: h => h (App)
}).$mount ('#app');


Android debug in some scripts that failed ahead other routes:
D/SystemWebChromeClient:
http://192.168.1.4:7070/static/libraries/leaflet/leaflet.markercluster.js:
Line 6 : Uncaught ReferenceError: L is not defined
I/chromium: [INFO:CONSOLE(6)] "Uncaught ReferenceError: L is not defined",
source:
http://192.168.1.4:7070/static/libraries/leaflet/leaflet.markercluster.js
(6)

i think i start to get it, android apk should contain all scripts, and no
need server....this way it should try get though since i let server open
that port...




André Lopes <aglopes.monitar@gmail.com> escreveu no dia segunda, 1/10/2018
à(s) 23:29:

**Comment by aglopes-monitar** [comment]
also tested somethings looks like some components are null in
mount(){}lifecycle, if i place mounted and inside a nexttick they no
longuer null ...


André Lopes <aglopes.monitar@gmail.com> escreveu no dia segunda, 1/10/2018
à(s) 23:47:

**Comment by aglopes-monitar** [comment]
would be much more easy to understand all this cordova vue plugin with an
elaborated example

André Lopes <aglopes.monitar@gmail.com> escreveu no dia segunda, 1/10/2018
à(s) 23:52:

**Comment by m0dch3n** [comment]
`npm run cordova-serve-android` creates an apk, with an app with a webview pointing to your dev server.

`npm run cordova-build-android` creates an apk, with an app with a webview pointing to index.html locally (file:///android_asset/www/index.html) and all your static files from the public folder are available under file:///android_asset/www/*

So public/static/js/jquery.js will be i.e. file:///android_asset/www/static/js/jquery.js ...
 
PS: Make sure your app works with hash router mode, because with cordova's local file system, you are not able to rewrite paths, nor to change the base path...

**Comment by m0dch3n** [comment]
BTW I now see, that you don't use hash router mode in your app, thats why scripts do longer work, if you refresh!

In history mode, when you open '/' it opens index.html, when you then redirect the vue router to /auth/login, your browser is showing /auth/login but is still serving the page /index.html ...

When you refresh now, the browser is longer serving /index.html, but /auth/login, so the base path changed, and your relativ url's are no longer correct...

With a vue router in hash mode, your browser is always serving index.html, and when your redirect to /auth/login, the router will redirect to index.html#/auth/login ... when you now refresh the page, your base path, will not change...

**Comment by aglopes-monitar** [comment]
npm run cordova-serve-android -> runs perfectly
i will try get everything to run in smaller app tomorow...
yes router was on history mode!



m0dch3n <notifications@github.com> escreveu no dia terça, 2/10/2018 à(s)
00:05:

**Comment by m0dch3n** [comment]
PS: 
if you prefer history mode, that's no problem, as long, as you are building for web with 
`npm run serve` or `npm run build`

However for cordova, you need hash mode

That's why the generator.js from this plugin tries to modify router.js from
`mode: 'history'`
to
`mode: process.env.CORDOVA_PLATFORM ? 'hash' : 'history'`
