### ISSUE TITLE
"baseUrl" is not allowed to be empty

### ISSUE THREAD

**Issue by stepinus** [m0dch3n/vue-cli-plugin-cordova#19]
this plugin set baseUrl in vue.config.js to '', but on build vue-cli throws error :
"Invalid options in vue.config.js: child "baseUrl" fails because ["baseUrl" is not allowed to be empty]"

**Comment by m0dch3n** [comment]
https://github.com/vuejs/vue-cli/issues/900

Maybe it's related to something like this, so I think, this got already fixed in a more recent vue cli... I never experienced this issue.

**Comment by stepinus** [comment]
> Which vue cli version do you use? How can I reproduce the error?



> [vuejs/vue-cli#900](https://github.com/vuejs/vue-cli/issues/900)
> 
> Maybe it's related to something like this, so I think, this got already fixed in a more recent vue cli... I never experienced this issue.

thank you, my vue-cli version is  3.0.5 , but  i will try to reinstall it and check

**Comment by m0dch3n** [comment]
The docs are saying:

`The value can also be set to an empty string ('') or a relative path (./) so that all assets are linked using relative paths. This allows the built bundle to be deployed under any public path, or used in a file system based environment like a Cordova hybrid app.`

https://cli.vuejs.org/config/#baseurl

**Comment by m0dch3n** [comment]
I had 3.0.1, tried now with 3.0.5, still not experiencing the problem...

**Comment by LaraFranklin** [comment]
@vue/cli-service": "^4.1.2" => remplace baseUrl by publicPath = ('')
