### ISSUE TITLE
Can we pass args to cordova run/build commands?

### ISSUE THREAD

**Issue by eladcandroid** [m0dch3n/vue-cli-plugin-cordova#20]
We need to pass a buildFlag argument according to this Cordova ios issue: https://github.com/apache/cordova-ios/issues/407

**Comment by m0dch3n** [comment]
Hmmm, I'm asking myself how the command api should look like, because currently the args are passed to the vue cli service...

**Comment by m0dch3n** [comment]
I mean these arguments:

https://github.com/vuejs/vue-cli/blob/7c91a187e46d7bb9a9b83bcdf97631794ac36b10/packages/%40vue/cli-service/lib/commands/serve.js#L18

Should we drop support for them and pass all the arguments to cordova?

**Comment by m0dch3n** [comment]
In the issue they are also talking about a build.json, maybe this is a temporary solution, until they release their new major ios version...

**Comment by m0dch3n** [comment]
I prefer if the vue plugin doesn't handle all the special cordova stuff... In fact, the problem is, that, in the long term, you can't come arround to know how cordova works, how you add plugins, configure your config.xml etc...

Nevertheless, having the possibility of having args is maybe a good idea, however as mentioned, how would you distinct between args passed to vue serve/build and cordova run/build ?

After thinking about this, maybe we can add some sort of -interactive flag to vue, which then prompts the user to add args, before executing cordova run/build
