### ISSUE TITLE
Need some clarifications

### ISSUE THREAD

**Issue by valh1996** [m0dch3n/vue-cli-plugin-cordova#22]
Hello,

First of all, congratulations for your work!

I tried your plugin. However, for this to work, I have to have my phone on the same wifi as my laptop.
(`$ npm run cordova-serve-android`)

Otherwise a blank page will be displayed. Do you have any explanation for this please?

Moreover, can you detail the points below please?:

- What this means in practice: `You need to handle cordova's "deviceready" etc in your app`
- Is it possible to do live reloading directly on the phone?
- What is the best solution to develop and test without application directly on the phone in your opinion?

Thank you for your attention.

**Comment by m0dch3n** [comment]
Thanks!

The blank page comes from :

 `In development mode`

* Pointing the cordova config.xml to Dev Server

So the webview of the cordova is simply showing the page of your dev server. Because of this, hot reloading etc is also working... If you want an app, which works without the dev server, you need to run cordova-build-*

`deviceready`

The plugin did not touch (modify) your vuejs app, because deviceready handling is not always needed... It depends on your usecase...

I can't say, which is the best solution how to develop the app, because it depends also on your usecase... 

In my usecase, I developped a responsive webapp mostly on the laptop, and tried only push notifications on the phone... I did not need, any other cordova or native stuff from the phone...
