### ISSUE TITLE
Cloning the project

### ISSUE THREAD

**Issue by evinkuraga** [m0dch3n/vue-cli-plugin-cordova#39]
Firstly, thank you for this fantastic package! This repo is worth it's share of gold. :)

This worked perfectly on a new installation, but what about if a project is cloned? It's missing all the node files, Cordova etc. 

I figured the steps to get this up and running again would be to run:
1: checkout the project
2: add any global global packages like vuecli & Cordova and any required emulation software and such
3: run npm install in root and inside src-cordova
4: vue add cordova ?
5:  run which ever npm script to get the app running 

However, I'm getting a no platforms installed issue and when I try to run Cordova based commands such as "Cordova prepare", I get "Current working directory is not a Cordova-based project."

It might be a good to put install steps for existing projects on the read.me?

**Comment by evinkuraga** [comment]
To all people who fall on this issue in the future, here's how I managed to resolve this:
Make sure you have a www directory in your src-cordova folder. 

If you ran the vue add Cordova command, make sure it didn't break the files you had before or revert them to their original form.

**Comment by m0dch3n** [comment]
I somehow missed this issue, because the owner closed it by himself already...

When I'm pulling from repo, I'm doing 

npm install
cd src-cordova
cordova add plaform android
cordova add platform ios
cd.. 

Maybe we can introduce a new command also for this, to avoid to the steps manually

**Comment by m0dch3n** [comment]
PS

vue add cordova

Is the wrong way, because it's like `vue create` command, which you also don't do, if you clone from repository... The reason is, `vue add`, will execute `cordova create` command, and then cordova add platform... 

So you can say:

`npm install` is "equal" to `cordova add platform`

**Comment by syonip** [comment]
I agree that `cordova platform add` is ok to run, but the things is it doesn't work either. You get an error:
```
cd src-cordova
cordova platform add android
Current working directory is not a Cordova-based project.
```

This happens because the `www` folder is not in source control (it's added to gitignore by the plugin). So you first need to create an empty folder `www` and then you can run the cordova commands.

You can clone this sample repo to see it: https://github.com/syonip/vue-csv-sample

**Comment by syonip** [comment]
I've tested this in my repo, and it seems to not make the empty folder tracked by git.
This [SO answer](https://stackoverflow.com/a/5581995/2942294 ) suggests adding an inner .gitignore file to the www folder, and this seems to work.

**Comment by syonip** [comment]
cool shall I try to add this to the plugin and PR?

**Comment by m0dch3n** [comment]
yes please, any help is appreciated! Thanks

**Comment by m0dch3n** [comment]
Please also create an issue for it then, and use

fix #issueid as commit message, so that it will be referenced automatically in changelog on new release

**Comment by m0dch3n** [comment]
or use this one with

`fix #39`

**Comment by syonip** [comment]
@m0dch3n did you get a change to review my PR?

**Comment by m0dch3n** [comment]
yes, but did not have time to test and verify, sorry

**Comment by syonip** [comment]
no worries :)
