### ISSUE TITLE
Properly importing Cordova Plugins

### ISSUE THREAD

**Issue by zintj** [m0dch3n/vue-cli-plugin-cordova#59]
So I've noticed in your docs you mention how to install cordova plugins as usual. I noticed this adds the plugin to the node_modules folder within src-cordova. Could you let me know how to actually import this plugin properly in a .vue file. For example, when trying to:

`import BackgroundGeolocation, {
...
} from "cordova-background-geolocation-lt";`

the plugin itself won't be found because it's not in the node_modules of the main Vue project.

**Comment by m0dch3n** [comment]
good question, I did never run into this issue, because the plugins I used were i.e. https://github.com/arnesson/cordova-plugin-firebase which registers it's API under window.FirebasePlugin whereas the code of the API etc was all in the builded `cordova.js`file

So cordova is building everything for you, and you only need to include the `cordova.js` file in your vue project to have the API... 

In my vue project I'm simply doing then

`if (window.FirebasePlugin)`

So I did never need to build myself the features I wanted from the plugin, and it always was enough to simply include the cordova.js file, which was builded by cordova...

I guess you already tried, to see, what happens when you install it in the main Vue project too with 

`npm install cordova-background-geolocation-lt --save` 

Maybe this is enough, because basically, it seems, your plugin is not being added to the builded `cordova.js` file...

But I don't know the whole build process of cordova enough, to really help you on this special case...

Also if you need to build the vue app, with a dependancy to a cordova plugin like this, makes your vue app no longer multiplatform usuable...

**Comment by m0dch3n** [comment]
@zintj did this solve your problem ?

**Comment by ssendev** [comment]
I have a similar problem but related to typescript. That is the types aren't present in the Vue project. So while  e.g. `cordova-plugin-file` provides types they aren't imported. 
Adding it to both projects seams to help with the types but that can't be done for `cordova` since there's one for each platform. Maybe it works to import all or just one but duplicating all packages across both projects seems to be the wrong approach.

**Comment by allanvb** [comment]
Did anyone found solution for this issue ?
