### ISSUE TITLE
Cordova Electron Platform

### ISSUE THREAD

**Issue by LLBlumire** [m0dch3n/vue-cli-plugin-cordova#61]
Would it be possible to add electron support

https://cordova.apache.org/docs/en/latest/guide/platforms/electron/index.html

I played around with adding it in a fork of my own and got it working for `cordova-build-electron` but `cordova-serve-electron` would not properly use the most up to date version of the app and would instead use the most recent version created with `cordova-build-electron`.

https://github.com/LLBlumire/vue-cli-plugin-cordova

**Comment by m0dch3n** [comment]
looks nice!

It seems `cordova-serve-electron` is not pointing to the devserver but to the build (src-cordova/www) folder... When you run `cordova-build-electron` cordova builds the vue app and outputs to src-cordova/www....

For `cordova-serve-electron` and HOT reload, I don't know electron enough, but you maybe have 2 possibilities

1. set the "startpage" of electron to the url of the devserver, as my plugin does with `<content src="http://192.168.1.10:8080" /><allow-navigation href="http://192.168.1.10:8080" />` in config.xml (and which seems to be ignored for electron for whatever reason)
2. create an index.html in www folder, with a fullscreen iframe, pointing to the devserver... 

HOWEVER, maybe the reason for this behaviour is also simply, because electron does not allow to let an "external" website communicate with the "internal" API... So I don't know if this is already enough, and will work seamlessly with the native part....

If you get this fixed, I can merge a PR to this repo and push to npm

**Comment by m0dch3n** [comment]
hey, are there any news on this? did you get it to work with HOT reload?

**Comment by m0dch3n** [comment]
Sorry, but if HOT reload is not working, the plugin is not so useful, for electron development... If you get it working, feel free, to reopen this issue again ;)
