### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by alexandrmiee** [m0dch3n/vue-cli-plugin-cordova#73]
An error appears when building via the cordova-serve-browser
`Uncaught SyntaxError: Unexpected token <`

I compiled the application through cordova-build-android and signed it.
When I try to install the application on the phone, the vue does not start. I only see index.html and all that in `<div id="app"></div>` is not mounted.

Can these two errors be related?

**Comment by m0dch3n** [comment]
do you have this error with a freshly created app? if not, check your dependencies, code etc, if they have somewhere a syntax error...

does your app work with npm run serve?

**Comment by alexandrmiee** [comment]
npm run serve works correctly and without errors

**Comment by m0dch3n** [comment]
ok, anyway, open the app in the browser, when you run cordova-serve-android and check 2hich script has the syntax error in the console... I suppose it's a cordova plugin, or something else...

**Comment by alexandrmiee** [comment]
I'll check it out this weekend.

**Comment by m0dch3n** [comment]
ok, I'll close this issue too, because I don't think, it's plugin related, but specific to your setup/configuration and does not need any code changes from the cordova plugin side...

Because npm run serve works, it must be something cordova related, which only gets triggered, when you include the JS files from cordova... Basically that's also the only thing, this vue plugin does.It executes vue and cordova commands, and only includes the cordova js files...

Unfortunately I can't and will not give any cordova specific support. (Unless, I can help, within a few minutes because I know what it could be)

If you feel, that this vue cordova plugin needs to adapt the code, to handle your specific problem, feel free, to reopen the issue again.
