### ISSUE TITLE
How to specify device target

### ISSUE THREAD

**Issue by stephanedemotte** [m0dch3n/vue-cli-plugin-cordova#75]
Hello, i want to specify a device target but i don't find how.

I've succeed with cordova with `cordova run ios --target="iPad-Air"` but the livereload don't work.

An idea ?

Thanks !!

**Comment by m0dch3n** [comment]
please [search for build.json](https://github.com/m0dch3n/vue-cli-plugin-cordova/issues?utf8=%E2%9C%93&q=is%3Aissue+build.json)

**Comment by m0dch3n** [comment]
basically the problem is, that current params are passed to the vue-cli serve command, and not to the cordova app.

it's possible to change this behaviour, but then all params are passed to cordova command, and if you want to parametize your vue-cli command, you need to adapt vue.config.js

There is still an open discussion about [this](https://github.com/m0dch3n/vue-cli-plugin-cordova/issues/26)

**Comment by iKnowMagic** [comment]
I created a small fix to address this issue. See #102

**Comment by m0dch3n** [comment]
I think target will not be used by vue cli, so I'm ok with this
