### ISSUE TITLE
Deploying on ios real device

### ISSUE THREAD

**Issue by chrschae** [m0dch3n/vue-cli-plugin-cordova#91]
Hello, i cant figure out how to deploy on a real ios device with cordova-serve-ios. Is there some alternative command i can use or something? Thanks in advance!

**Comment by m0dch3n** [comment]
This is more cordova related, than plugin related, unfortunately currently you can't pass arguments to the cordova commands by this command, but only to the vue cli command...

More info why, is here https://github.com/m0dch3n/vue-cli-plugin-cordova/issues/26

More info about Cordova IOS deploy can be found here https://cordova.apache.org/docs/en/latest/guide/platforms/ios/index.html

This plugin basically just executes 2 commands, when you run serve...

`npm run serve` (but the served app will be bundled with cordova stuff etc)
`cordova run ios` (build and run cordova app... as the builded cordova app is pointing to your dev server and not the static files within the builded app, you have hot reload etc working...

On build, it's the same:
`npm run build` 
`cordova build ios`, but this time, the app will no longer point to your devserver, but show the static files inside your bundled app...

So when you need to add params to the cordova command, one solution would be to use `build.json`

What you also can do is:

```
run cordova-serve-ios
then open xcode
open the project workspace under: `src-cordova/platforms/ios/YourAppName.xcworkspace`
then run this app on your device! (Don't open the `xcodeproj`! The builded app needs CocoaPods to be working...)
```
From command line, you can also use 
`ios-deploy` by installing it with `npm install -g ios-deploy`

And sometimes for special things and cases, not covered by this plugin, I also simply just do:
```
cd src-cordova
run my specific cordova command
```

**Comment by chrschae** [comment]
is there a way to also have Hot Module Replacement when i deploy my  ios app?
I tried to give parameters with build.json, but no luck...
On Android it works fine, because on Android it takes device as standard target if it is connected, but on ios it always starts emulator

**Comment by m0dch3n** [comment]
make sure, the ios app you are building and running on your ios device is pointing to your devserver and not the files in src-cordova/www

**Comment by chrschae** [comment]
Sorry, im new to all this. You mean i have to point to my devserver in Xcode? Or can i point my app to the devserver in some config file in src-cordova?

**Comment by m0dch3n** [comment]
on cordova-serve commands this plugin runs a hook, which modifies the config.xml from cordova to not point to the index.html file, but to your dev server... 

the config.xml of cordova defines the starting point of you webview...

https://cordova.apache.org/docs/en/latest/config_ref/index.html

https://cordova.apache.org/docs/en/latest/config_ref/index.html#content
> Defines the app's starting page in the top-level web assets directory. The default value is index.html, which customarily appears in a project's top-level www directory

**Comment by m0dch3n** [comment]
anyway, sorry, but I'll stop supporting your specific the cordova problems now, as there is many documentation available already, and this is out of the support I can give in my free time...

This issue tracker should mainly be used for issues about the plugin code etc, then as discussion board...

**Comment by vesper8** [comment]
@chrschae did you get this to work in the end? I love how `npm run cordova-serve-android` will automatically launch on your real Android device if it's connected to your laptop via USB, and then hot reload just works which is great because you get the full performance of using your phone instead of a slow emulator, and you get instant updates as you develop your app

did you figure out how to get this to work for an IOS device? I too am annoyed at having to develop via the IOS Simulator because I find it much slower compared to the real phone

**Comment by m0dch3n** [comment]
@vesper8 you can run 

`npm run cordova-serve-ios`, leave this command running, because you need the devserver, then open  xcode, open the .xcworkspace file, and run it on real device with hot reload... 

or maybe (but I did not try) there is a new param now which helps:

https://github.com/m0dch3n/vue-cli-plugin-cordova/pull/102
